Restructure (again) to simplify
I believe I'm making this too hard. Let's try something a bit more
straightforward. And oh.. swap distro while were at it. Debian is much
closer to our working platform anyway.

diff --git a/.bash/osx/finder_cd b/.bash/osx/finder_cd
--- a/.bash/osx/finder_cd
+++ b/.bash/osx/finder_cd
@@ -3,14 +3,8 @@
 # By @sindresorhus taken from:
 # https://github.com/paulirish/dotfiles/commit/e67d1bc03
 # @todo: could use a darwin check
-finder_cd() {
-  if ! command -v osascript >/dev/null
-  then
-    echo "/!\ osascript is unavailable.  Aborting.. (~/.bash/osx/finder_cd)"; return
-  fi
-  cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
-}
-if [[ "$1" != "${INIT_KEYWORD}" ]]
+if ! command -v osascript >/dev/null
 then
-  finder_cd
+  echo "/!\ osascript is unavailable.  Aborting.. (~/.bash/osx/finder_cd)"; return
 fi
+cd "`osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)'`"
diff --git a/.bash/ssh/ssh_config_autocomplete_load b/.bash/ssh/ssh_config_autocomplete_load
--- a/.bash/ssh/ssh_config_autocomplete_load
+++ b/.bash/ssh/ssh_config_autocomplete_load
@@ -2,14 +2,10 @@
 # adds ~/.ssh/config to the ssh autocomplete
 # Call whenever ssh host config changes (@see ssh_configure_host)
 # @TODO: experiment with file listener to update autocomplete automatically
-ssh_config_autocomplete_load() {
-  if ! command -v awk >/dev/null
-  then
-    echo "/!\ awk is unavailable.  Aborting..(~/.bash/ssh/ssh_config_autocomplete_load)"; return
-  fi
-  complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' ~/.ssh/{config,conf.d/*.conf})" ssh
-}
-if [[ "$1" != "${INIT_KEYWORD}" ]]
+if ! command -v awk >/dev/null
 then
-  ssh_config_autocomplete_load
+  echo "/!\ awk is unavailable.  Aborting..(~/.bash/ssh/ssh_config_autocomplete_load)"; return
 fi
+dir="$HOME/.ssh/{config,conf.d/*.conf}"
+echo "* completion \"ssh_config\" ${dir}"
+complete -W "$(awk '/^\s*Host\s*/ { sub(/^\s*Host /, ""); print; }' $HOME/.ssh/{config,conf.d/*.conf})" ssh
diff --git a/.bash/ssh/ssh_configure_host b/.bash/ssh/ssh_configure_host
--- a/.bash/ssh/ssh_configure_host
+++ b/.bash/ssh/ssh_configure_host
@@ -3,23 +3,16 @@
 # @param The identifier to use for this SSH host configuration.
 # @param The host name.
 # @param The username for that host.
-ssh_configure_host() {
-  local identifier=$1
-  local hostname=$2
-  local username=$3
-
-  if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]
-  then
-    echo "usage: ssh_configure_host <identifier> <hostname> <username>"
-  else
-    echo -e "Host $identifier\n\tHostName $hostname\n\tUser $username\n\tIdentityFile ~/.ssh/id_rsa\n\tForwardAgent yes" >> ~/.ssh/config
-    ssh $identifier 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
-    # # TODO Use ssh_test_key()?
-    tput bold; ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
-    ssh_config_autocomplete_load
-  fi
-}
-if [[ "$1" != "${INIT_KEYWORD}" ]]
+identifier=$1
+hostname=$2
+username=$3
+if [[ "$identifier" == "" ]] || [[ "$username" == "" ]] || [[ "$hostname" == "" ]]
 then
-  ssh_configure_host $@
+  echo "usage: ssh_configure_host <identifier> <hostname> <username>"
+else
+  echo -e "Host $identifier\n\tHostName $hostname\n\tUser $username\n\tIdentityFile ~/.ssh/id_rsa\n\tForwardAgent yes" >> ~/.ssh/config
+  ssh $identifier 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
+  # # TODO Use ssh_test_key()?
+  tput bold; ssh -o PasswordAuthentication=no $identifier true && { tput setaf 2; echo 'Success!'; } || { tput setaf 1; echo 'Failure'; }; tput sgr0
+  ssh_config_autocomplete_load
 fi
